project:
  type: website
  output-dir: docs
lang: es

website:
  title: "HackODS"
  search: false
  navbar:
    logo: img/logo.png
    left:
      - text: "Tableros ganadores"
        href: index.qmd
      - text: "2026"
        menu:
          - text: "Bienvenida 2026"
            href: 2026/bienvenida-2026.qmd
          - text: "---"
          - text: "Comunicación"
            href: 2026/comunicacion.qmd
          - text: "Rúbrica 20 equipos"
            href: 2026/rubrica20.qmd
          - text: "---"
          - text: "Calendario"
            href: 2026/calendario.qmd
          - text: "---"
          - text: "Mentorías"
            href: 2026/mentorias.qmd
          - text: "1ra mentoría"
            href: 2026/calendario-mentorias.qmd
          - text: "2da mentoría"
            href: 2026/calendario-2da-mentoria.qmd
          - text: "Comunidad"
            href: 2026/comunidad_mentorias.qmd
          - text: "Capacitación"
            href: 2026/capacitacion.qmd
          - text: "---"
          - text: "Política de IA"
            href: 2026/declaratoriaIA.qmd
          - text: "---"
          - text: "Finalistas"
            href: 2026/finalistas.qmd
          - text: "Jurado"
            href: 2026/jurado_final.qmd
          - text: "Rúbrica final"
            href: 2026/rubrica-final.qmd
          - text: "Programa"
            href: 2026/calendario-final.qmd
    tools:
      - icon: github
        href: https://github.com/hackods/hackods.github.io

  page-footer:
    background: gray
    left:
      - text: "HackODS UNAM 2026"
    center:
      - icon: instagram
        href: https://instagram.com/ierunam
        aria-label: Instagram IER UNAM
      - icon: instagram
        href: https://instagram.com/geofisica.unam
        aria-label: Instagram Geofísica
comments:
  hypothesis: false

format:
  html:
    theme:
      light: lux
      dark: superhero
    css: styles.css
