project:
  type: website
  output-dir: docs
lang: es

website:
  title: "HackODS"
  search: false
  navbar:
    logo: ./imagenes/logo_color.png
    left:
      - text: "Inicio"
        href: index.qmd#inicio
      - text: "Convocatoria"
        href: index.qmd#convocatoria
      - text: "Cronograma"
        href: index.qmd#cronograma
      - text: "Criterios"
        href: index.qmd#criterios
      - text: "Premios"
        href: index.qmd#premios
      - text: "Jurado"
        href: index.qmd#jurado
      - text: "Descalificación"
        href: index.qmd#descalificacion
      - text: "Premiación"
        href: index.qmd#entrega
      - text: "Contacto"
        href: index.qmd#contacto
    right:
      - text: "Inscríbete"
        href: index.qmd#registro

        
        

format:
  html:
    theme:
      - cosmo
    #   - brand
    css: styles.css

    # toc: true



