project:
  type: website
  output-dir: docs
lang: es

website:
  title: "HackODS"
  search: false
  navbar:
    logo: logo.png
    left:
      - text: "Tableros"
        href: tableros.qmd
      - text: "Capacitación"
        href: capacitacion.qmd
    tools:
      - icon: github
        href: https://github.com/hackods/hackods.github.io

  page-footer:
    background: gray
    left:
      - text: "HackODS UNAM 2026"
    center:
      - icon: instagram
        href: https://instagram.com/ierunam
        aria-label: Instagram IER UNAM
      - icon: instagram
        href: https://instagram.com/geofisica.unam
        aria-label: Instagram Geofísica
comments:
  hypothesis: false

format:
  html:
    theme:
      light: zephyr
      dark: darkly
    css: styles.css
