project:
  type: website
  output-dir: docs
lang: es

website:
  title: ""
  search: false
  navbar:
    logo: ./imagenes/logo_completo_blanco.png
    left:
      # - text: "¿Qué es?"
      #   href: index.qmd#hackods
      - text: "Convocatoria"
        href: index.qmd#convocatoria
      - text: "Cronograma"
        href: index.qmd#cronograma
      # - text: "Criterios"
      #   href: index.qmd#criterios
      - text: "Premios"
        href: index.qmd#premios
      # - text: "Jurado"
      #   href: index.qmd#jurado
      # - text: "Descalificación"
      #   href: index.qmd#descalificacion
      - text: "Premiación"
        href: index.qmd#entrega
      - text: "Contacto"
        href: index.qmd#contacto
    # right:
      # - text: "Inscríbete"
      #   href: index.qmd#registro
    


  page-footer: 
    background: gray
    left: 
      - text: "Copyright 2025" 
    center:  
      - icon: instagram
        href: https://instragram.com/HackODS_UNAM 
      - icon: twitter
        href: https://twitter.com/HackODS_UNAM 
        
      

        
        

format:
  html:    
    page-layout: full
    theme:
      - cosmo
    #   - brand
    css: styles.css

    # toc: true



