---
title: "Finalistas"
---

| Equipo | Integrantes |
|--------|-------------|
| 2, 3 datos | Daniela Lira Huerta, Jose David Chavez Tipa, Margarita Reyes Trujillo |
| Abejas Astutas | Adán Gael Salgado Ortega, Anthony Soto Vazquez, Kimberly Ramirez Becerril |
| ASHIRA | Melisa Asharet Arano Bejarano, Roberto Jhoshua Alegre Ventura, Israel Martínez Jiménez |
| Bladerunners | Luis Fernando Martínez Moreno, Guadalupe Herrera Barragán, Ana Lydia Herrera Macías |
| Código Guinda | José Francisco Pérez Ramón, Jaretzy Pérez Ramón, Elias Montejo Hernández |
| DatofilODS | Alma Diana Herrera Ortiz, Santiago Botero Sierra, Daniel Mondragon Tapia |
| DERRE | Emilio Axel Salas Palacios, Claudio Flores Guzmán, Angel Noel Pérez Martínez |
| EmprendeIA | Aljendro Valentin Saldaña Mendez, Eduardo Francisco Peñaloza Uribe, Tetsu Nicolas Osnaya Quevedo |
| HuerfanitosUTM | Mario Enrique Ramirez Gallardo, Irving Tristan Perez Zurita, Dante Neil Martinez Jimenez |
| linuxitOS | Jesús Sebastián Vázquez Zarco, Alejandro Naomi Muciño Hernández, Victor Federico Caldera Arellano |
| Lobo Ensambladores | Andrea Aparicio Guerrero, Kevin Mateos Coleptor, Luis Guillermo Rodríguez López |
| MareaDeDatODS | Utrera Hernández Sophia Alejandra, Vera Rodríguez Luis Enrique, Zepeda Saéz Zack David |
| PatosClimaticODS | Miguel Ángel Brito Liévano |
| PCABoys | Carlo Kiliano Ferrera Guadarrama, Aldo Sebastian Altamirano Vazquez, Jose Julian Perez Bustamante |
| Pumatécnicos | José Eduardo Pérez Castillo, Marco Antonio Pérez Castillo, Mariangely López González |
| Tlamatipohua | Milena Fernanda Rivera Hernández, Carlos Olamendi Rincón, Alejandro Cerda Barroso |
| Trío tristeza | Arturo Herrera Diaz, Luis Donaldo Martinez Torres, Eduardo Levi Leon Garcia |
| Typers | Cano García Enrique Emiliano, Cruz Mendoza Valentina Ayelen, Rodríguez Barrera Valeria Vianey |
| UPIIT Machine | Elisa Naomi Alvarado Sanchez, Ricardo Polock Suarez Geovani, Bryan Hernandez Alvarez |
| Voces ODS 2030 | Carlos Alberto Villa Tobon |
